print("Love you dad!!!")
print("Love you dad!!!")
print("Love you dad!!!")
print("")
print("")
print("")
print("       .....           .....")
print("   ,ad8PPPP88b,     ,d88PPPP8ba,")
print('  d8P"      "Y8b, ,d8P"      "Y8b')
print(" dP'            8a8             `Yd")
print(' 8(              "              )8')
print(" I8                             8I")
print("  Yb,                         ,dP")
print('   "8a,                     ,a8')
print('     "8a,                 ,a8"')
print('       "Yba             adP"')
print("         `Y8a         a8P'")
print("           `88,     ,88'")
print('             "8b   d8"')
print('              "8b d8"')
print('               `888')
print('                 "')
